version: 0.2

phases:
  install:
    commands:
      - echo "Installing nothing at all"
  build:
    commands:
      - echo "Zipping and deploying lambda files"
      - zip index_photos.zip index_photos.py
      - zip search_photos.zip search_photos.py
  post_build:
    commands:
      - echo "Pushing lambdas"
      - aws lambda update-function-code --function-name search-images-cloudformation --zip-file fileb://search_photos.zip
      - aws lambda update-function-code --function-name index-images-cloudformation --zip-file fileb://index_photos.zip
      - echo "Pushed successfully!!"
