version: 0.2

phases:
  install:
    commands:
      - echo "Installing nothing at all"
  build:
    commands:
      - echo "Zipping and deploying lambda files"
      - cp index-photos.py lambda_function.py
      - zip index_photos.zip lambda_function.py
      - cp search-images.py lambda_function.py
      - zip search_images.zip lambda_function.py
  post_build:
    commands:
      - echo "Pushing lambdas"
      - aws lambda update-function-code --function-name search-images-cloudformation --zip-file fileb://search_images.zip
      - aws lambda update-function-code --function-name index-images-cloudformation --zip-file fileb://index_photos.zip
      - echo "Pushed successfully!!"
